/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TimelockImport } from './routes/timelock'
import { Route as MessageImport } from './routes/message'
import { Route as EncryptedNotesImport } from './routes/encrypted-notes'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TimelockRoute = TimelockImport.update({
  id: '/timelock',
  path: '/timelock',
  getParentRoute: () => rootRoute,
} as any)

const MessageRoute = MessageImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => rootRoute,
} as any)

const EncryptedNotesRoute = EncryptedNotesImport.update({
  id: '/encrypted-notes',
  path: '/encrypted-notes',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/encrypted-notes': {
      id: '/encrypted-notes'
      path: '/encrypted-notes'
      fullPath: '/encrypted-notes'
      preLoaderRoute: typeof EncryptedNotesImport
      parentRoute: typeof rootRoute
    }
    '/message': {
      id: '/message'
      path: '/message'
      fullPath: '/message'
      preLoaderRoute: typeof MessageImport
      parentRoute: typeof rootRoute
    }
    '/timelock': {
      id: '/timelock'
      path: '/timelock'
      fullPath: '/timelock'
      preLoaderRoute: typeof TimelockImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/encrypted-notes': typeof EncryptedNotesRoute
  '/message': typeof MessageRoute
  '/timelock': typeof TimelockRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/encrypted-notes': typeof EncryptedNotesRoute
  '/message': typeof MessageRoute
  '/timelock': typeof TimelockRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/encrypted-notes': typeof EncryptedNotesRoute
  '/message': typeof MessageRoute
  '/timelock': typeof TimelockRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/encrypted-notes' | '/message' | '/timelock'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/encrypted-notes' | '/message' | '/timelock'
  id: '__root__' | '/' | '/encrypted-notes' | '/message' | '/timelock'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EncryptedNotesRoute: typeof EncryptedNotesRoute
  MessageRoute: typeof MessageRoute
  TimelockRoute: typeof TimelockRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EncryptedNotesRoute: EncryptedNotesRoute,
  MessageRoute: MessageRoute,
  TimelockRoute: TimelockRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/encrypted-notes",
        "/message",
        "/timelock"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/encrypted-notes": {
      "filePath": "encrypted-notes.tsx"
    },
    "/message": {
      "filePath": "message.tsx"
    },
    "/timelock": {
      "filePath": "timelock.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
